export const styles = {
  appContainer: {
    backgroundColor: "var(--bg-primary)",
    minHeight: "100vh",
    position: "relative" as const,
    fontFamily:
      "'Outfit', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    color: "var(--text-primary)",
    boxSizing: "border-box" as const,
  },
  dashboardContainer: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "40px 20px",
    display: "grid",
    gridTemplateColumns: "260px 1fr",
    gap: "30px",
    boxSizing: "border-box" as const,
  },
  sidebar: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "24px",
    backgroundColor: "var(--bg-secondary)",
    border: "1px solid var(--border-color)",
    borderRadius: "16px",
    padding: "24px",
    height: "fit-content",
    boxShadow: "0 4px 20px var(--color-primary-tint)",
    position: "sticky" as const,
    top: "40px",
  },
  sidebarBrand: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    paddingBottom: "16px",
    borderBottom: "1px solid var(--border-color)",
  },
  logoBadge: {
    width: "36px",
    height: "36px",
    borderRadius: "8px",
    background: "linear-gradient(135deg, var(--color-primary) 0%, var(--color-primary-hover) 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "18px",
    color: "var(--text-light)",
    fontWeight: "bold",
    boxShadow: "0 4px 12px var(--color-primary-tint)",
  },
  brandTitle: {
    fontSize: "15px",
    fontWeight: "bold",
    color: "var(--color-primary)",
  },
  brandSubtitle: {
    fontSize: "11px",
    color: "var(--text-secondary)",
    marginTop: "1px",
  },
  navGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  sidebarLink: {
    display: "flex",
    alignItems: "center",
    padding: "12px 14px",
    borderRadius: "8px",
    fontSize: "13px",
    fontWeight: "500",
    border: "none",
    textAlign: "left" as const,
    cursor: "pointer",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  sidebarFooter: {
    marginTop: "12px",
    paddingTop: "16px",
    borderTop: "1px solid var(--border-color)",
  },
  mainPanel: {
    flex: 1,
    minWidth: 0,
  },
  tabContent: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "24px",
  },
  sectionHeader: {
    marginBottom: "8px",
  },
  mainTitle: {
    fontSize: "24px",
    fontWeight: 800,
    color: "var(--color-primary)",
    margin: "0 0 6px 0",
    letterSpacing: "-0.5px",
  },
  mainSubtitle: {
    fontSize: "14px",
    color: "var(--text-secondary)",
    margin: 0,
    lineHeight: "1.4",
  },
  frameworksGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: "16px",
  },
  frameworkCard: {
    position: "relative" as const,
    backgroundColor: "var(--bg-secondary)",
    borderRadius: "12px",
    padding: "16px 18px",
    display: "flex",
    alignItems: "center",
    gap: "14px",
    boxSizing: "border-box" as const,
    overflow: "hidden",
  },
  cardHighlightDot: {
    position: "absolute" as const,
    width: "3px",
    height: "24px",
    left: 0,
    top: "calc(50% - 12px)",
    borderRadius: "0 4px 4px 0",
    backgroundColor: "transparent",
  },
  cardIconBox: {
    width: "38px",
    height: "38px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "18px",
    flexShrink: 0,
  },
  cardFrameworkName: {
    fontSize: "13px",
    fontWeight: "600",
    color: "var(--text-primary)",
  },
  cardFrameworkSubtitle: {
    fontSize: "11px",
    color: "var(--text-secondary)",
    marginTop: "2px",
    lineHeight: "1.3",
  },
  cardActiveCheck: {
    width: "18px",
    height: "18px",
    borderRadius: "50%",
    backgroundColor: "var(--color-primary)",
    color: "var(--text-light)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "10px",
    fontWeight: "bold",
    flexShrink: 0,
  },
  previewContainer: {
    backgroundColor: "#1e1e1e", // Fixed dark gray editor background
    border: "1px solid #333333", // Fixed dark border
    borderRadius: "12px",
    overflow: "hidden",
  },
  previewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    backgroundColor: "#161b22", // Fixed dark header background
    borderBottom: "1px solid #333333", // Fixed dark border
  },
  pulseDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "var(--color-primary)",
    boxShadow: "0 0 8px var(--color-primary)",
  },
  previewBody: {
    padding: "20px",
    overflowX: "auto" as const,
  },
  codePre: {
    margin: 0,
    backgroundColor: "transparent",
    fontFamily: "'JetBrains Mono', Consolas, Monaco, monospace",
    fontSize: "13px",
    lineHeight: "1.6",
  },
  card: {
    backgroundColor: "var(--bg-card)",
    border: "1px solid var(--border-color)",
    borderRadius: "12px",
    padding: "24px",
    boxSizing: "border-box" as const,
  },
  cardTitle: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "var(--color-primary)",
    margin: "0 0 16px 0",
  },
  infoCard: {
    backgroundColor: "var(--bg-primary)",
    border: "1px solid var(--border-color)",
    borderRadius: "12px",
    padding: "20px",
    boxSizing: "border-box" as const,
  },
  codeText: {
    color: "var(--color-primary)",
    backgroundColor: "var(--color-primary-tint)",
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "12px",
    fontFamily: "monospace",
  },
  priorityPillContainer: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "10px",
    margin: "16px 0",
  },
  priorityPill: {
    backgroundColor: "var(--bg-primary)",
    border: "1px solid var(--border-color)",
    padding: "6px 12px 6px 14px",
    borderRadius: "20px",
    fontSize: "12px",
    display: "inline-flex",
    alignItems: "center",
    gap: "10px",
  },
  pillButton: {
    background: "none",
    border: "none",
    color: "var(--text-secondary)",
    cursor: "pointer",
    padding: "2px 4px",
    fontSize: "11px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  addTagWrapper: {
    display: "flex",
    gap: "10px",
    marginTop: "20px",
    alignItems: "center",
  },
  radioContainer: {
    display: "flex",
    gap: "16px",
    margin: "4px 0",
  },
  radioLabel: {
    display: "inline-flex",
    alignItems: "center",
    cursor: "pointer",
    fontSize: "13px",
    color: "var(--text-primary)",
  },
  textareaHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "6px",
  },
  textareaTag: {
    fontSize: "10px",
    color: "var(--text-secondary)",
    backgroundColor: "var(--bg-primary)",
    padding: "2px 6px",
    borderRadius: "4px",
    fontFamily: "monospace",
  },
  codeTextarea: {
    fontFamily: "'JetBrains Mono', Consolas, Monaco, monospace",
    fontSize: "12px",
    lineHeight: "1.5",
    width: "100%",
    boxSizing: "border-box" as const,
    resize: "vertical" as const,
  },
  compilerLabel: {
    fontSize: "11px",
    textTransform: "uppercase" as const,
    fontWeight: "bold",
    color: "var(--text-secondary)",
    marginBottom: "4px",
  },
  compilerBox: {
    backgroundColor: "#1e1e1e", // Fixed dark gray editor background
    border: "1px solid #333333", // Fixed dark border
    color: "#d4d4d4", // Fixed default text color
    borderRadius: "8px",
    padding: "12px",
    fontFamily: "'JetBrains Mono', Consolas, Monaco, monospace",
    fontSize: "12px",
    lineHeight: "1.5",
    overflowX: "auto" as const,
  },
  tokenRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "8px 12px",
    backgroundColor: "var(--bg-primary)",
    borderRadius: "8px",
    border: "1px solid var(--border-color)",
  },
  tokenCode: {
    color: "var(--color-primary)",
    fontWeight: "bold",
    fontSize: "13px",
    fontFamily: "monospace",
    minWidth: "50px",
  },
  tokenDesc: {
    fontSize: "12px",
    color: "var(--text-secondary)",
  },
  aboutLink: {
    display: "inline-flex",
    alignItems: "center",
    padding: "10px 16px",
    borderRadius: "8px",
    border: "1px solid var(--border-color)",
    color: "var(--color-primary)",
    textDecoration: "none",
    fontSize: "13px",
    fontWeight: "500",
    transition: "all 0.2s ease",
    backgroundColor: "var(--bg-secondary)",
  },
};
