export const styles = {
  btnStartRecord: {
    background: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    padding: "3px 8px",
    fontSize: "10px",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(16, 185, 129, 0.2)",
  },
  btnStopRecord: {
    background: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    padding: "3px 8px",
    fontSize: "10px",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(239, 68, 68, 0.2)",
  },
  pulseRedDot: {
    display: "inline-block",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#ff4d4d",
    boxShadow: "0 0 0 0 rgba(255, 77, 77, 0.7)",
  },
  greenDot: {
    display: "inline-block",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#4ade80",
  },
  appContainer: {
    backgroundColor: "#181a1b",
    color: "#cccccc",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column" as const,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    fontSize: "11px",
  },
  navBar: {
    borderBottom: "1px solid #2d2d2d",
    backgroundColor: "#252526",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 4px",
    height: "26px",
    userSelect: "none" as const,
    minHeight: "26px",
  },
  tabsList: {
    display: "flex",
    listStyle: "none",
    margin: 0,
    padding: 0,
    height: "100%",
    alignItems: "stretch",
  },
  tabItem: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    margin: 0,
    padding: 0,
  },
  link: {
    color: "#969696",
    padding: "0 8px",
    fontSize: "11px",
    fontWeight: "normal",
    height: "100%",
    display: "flex",
    alignItems: "center",
    borderBottom: "2px solid transparent",
    transition: "color 0.2s, border-color 0.2s",
    textDecoration: "none",
  },
  activeLink: {
    color: "#ffffff",
    padding: "0 8px",
    fontSize: "11px",
    fontWeight: "500",
    height: "100%",
    display: "flex",
    alignItems: "center",
    borderBottom: "2px solid #0e639c",
    textDecoration: "none",
  },
  settingsBtn: {
    padding: "0 6px",
    cursor: "pointer",
    fontSize: "18px",
    color: "#858585",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    transition: "color 0.2s",
    size: "16px",
  },
  contentBody: {
    padding: "6px",
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflowY: "auto" as const,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center" as const,
    color: "#777",
    marginTop: "40px",
    padding: "12px",
  },
  emptyTitle: {
    fontSize: "11px",
    fontWeight: "bold",
    color: "#bbbbbb",
    marginBottom: "2px",
  },
  emptySubtitle: {
    fontSize: "10px",
    maxWidth: "220px",
    lineHeight: "1.3",
  },
  locatorList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
  },
  locatorRow: {
    display: "flex",
    alignItems: "center",
    padding: "3px 4px",
    borderBottom: "1px solid #252526",
    gap: "4px",
    backgroundColor: "#1e1e1e",
    borderRadius: "2px",
  },
  labelBox: {
    display: "flex",
    alignItems: "center",
    gap: "3px",
    flexShrink: 1,
    flexGrow: 0,
    width: "84px",
    minWidth: "40px",
    overflow: "hidden",
  },
  priorityBadge: {
    backgroundColor: "#37373d",
    color: "#858585",
    fontSize: "9px",
    fontWeight: "bold",
    borderRadius: "2px",
    padding: "1px 3px",
    display: "inline-block",
    textAlign: "center" as const,
    minWidth: "12px",
  },
  locatorLabel: {
    fontSize: "10px",
    color: "#aaaaaa",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  codeSnippet: {
    flex: 1,
    minWidth: "20px",
    backgroundColor: "#151515",
    color: "#4ec9b0",
    border: "1px solid #2d2d2d",
    borderRadius: "2px",
    padding: "2px 4px",
    fontSize: "10px",
    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    cursor: "pointer",
    userSelect: "all" as const,
  },
  actionSelect: {
    appearance: "auto" as any,
    WebkitAppearance: "auto" as any,
    backgroundColor: "#252526",
    color: "#cccccc",
    border: "1px solid #3c3c3c",
    borderRadius: "2px",
    padding: "1px 2px",
    fontSize: "10px",
    width: "72px",
    minWidth: "72px",
    flexShrink: 0,
    cursor: "pointer",
    outline: "none",
    height: "18px",
  },
  toast: {
    position: "fixed" as const,
    bottom: "12px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 9999,
    padding: "4px 10px",
    borderRadius: "4px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.5)",
    border: "1px solid #0e639c",
    background: "#0e639c",
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: "10px",
  },
  tableCard: {
    backgroundColor: "#202020",
    borderLeft: "3px solid #ffb86c",
    padding: "4px 6px",
    marginBottom: "4px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
    borderRadius: "2px",
  },
  tableHeader: {
    fontSize: "10px",
    fontWeight: "bold",
    color: "#ffb86c",
  },
  tableRow: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  tableLabel: {
    fontSize: "9px",
    color: "#888",
    width: "80px",
    minWidth: "80px",
  },
  tableCode: {
    flex: 1,
    backgroundColor: "#151515",
    color: "#ffb86c",
    border: "1px solid #2d2d2d",
    borderRadius: "2px",
    padding: "2px 4px",
    fontSize: "10px",
    fontFamily: "Consolas, Monaco, monospace",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  axesContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    padding: "2px",
  },
  axesResultBox: {
    backgroundColor: "#151515",
    border: "1px solid #2d2d2d",
    borderRadius: "2px",
    padding: "4px 6px",
  },
  axesResultCode: {
    color: "#569cd6",
    fontSize: "10px",
    fontFamily: "Consolas, Monaco, monospace",
    fontWeight: "bold",
    cursor: "pointer",
    wordBreak: "break-all" as const,
    background: "none",
    padding: 0,
  },
  axesColumns: {
    display: "flex",
    gap: "4px",
    marginTop: "2px",
  },
  axesColumn: {
    flex: 1,
    border: "1px solid #2d2d2d",
    borderRadius: "2px",
    padding: "4px",
    backgroundColor: "#202020",
    maxHeight: "160px",
    overflowY: "auto" as const,
  },
  columnHeader: {
    fontSize: "9px",
    color: "#888",
    fontWeight: "bold",
    marginBottom: "4px",
    textTransform: "uppercase" as const,
    borderBottom: "1px solid #2d2d2d",
    paddingBottom: "2px",
  },
  radioWrapper: {
    margin: "2px 0",
  },
  radioLabel: {
    color: "#cccccc",
    fontSize: "10px",
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    userSelect: "none" as const,
  },
  toolCard: {
    backgroundColor: "#202020",
    border: "1px solid #2d2d2d",
    borderRadius: "2px",
    padding: "6px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
  },
  toolTitle: {
    fontSize: "10px",
    fontWeight: "bold",
    color: "#ffffff",
  },
  toolDesc: {
    fontSize: "9px",
    color: "#666",
    marginBottom: "2px",
  },
  toolInput: {
    backgroundColor: "#151515",
    color: "#cccccc",
    border: "1px solid #2d2d2d",
    borderRadius: "2px",
    padding: "2px 4px",
    fontSize: "10px",
    outline: "none",
    flex: 1,
    height: "20px",
  },
  btnFind: {
    border: "none",
    backgroundColor: "#0e639c",
    color: "#ffffff",
    padding: "2px 6px",
    fontSize: "10px",
    borderRadius: "2px",
    cursor: "pointer",
    fontWeight: "500",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  btnClear: {
    border: "none",
    backgroundColor: "transparent",
    color: "#f44336",
    padding: "2px 4px",
    fontSize: "10px",
    cursor: "pointer",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  btnVerifyInline: {
    border: "none",
    backgroundColor: "#0e639c",
    color: "#ffffff",
    padding: "1px 4px",
    fontSize: "9px",
    borderRadius: "2px",
    cursor: "pointer",
    height: "18px",
    width: "32px",
    minWidth: "32px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "4px",
    fontWeight: "500" as any,
  },
  searchSuccess: {
    marginTop: "2px",
    color: "#4ade80",
    fontSize: "10px",
  },
  searchFail: {
    marginTop: "2px",
    color: "#f44336",
    fontSize: "10px",
  },
  convertBox: {
    marginTop: "4px",
    backgroundColor: "#151515",
    border: "1px solid #2d2d2d",
    padding: "4px",
    borderRadius: "2px",
  },
  convertCode: {
    color: "#4ade80",
    fontSize: "10px",
    fontFamily: "Consolas, Monaco, monospace",
    cursor: "pointer",
    wordBreak: "break-all" as const,
    background: "none",
    padding: 0,
  },
  aboutCard: {
    backgroundColor: "#202020",
    border: "1px solid #2d2d2d",
    borderRadius: "2px",
    padding: "8px",
  },
  divider: {
    height: "1px",
    backgroundColor: "#2d2d2d",
    margin: "6px 0",
  },
  linkRow: {
    display: "flex",
    gap: "8px",
  },
  aboutLink: {
    color: "#3794ff",
    fontSize: "10px",
    textDecoration: "none",
  },
};
