export const styles = {
  btnStartVideo: {
    background: "var(--color-primary)",
    color: "var(--text-light)",
    border: "1px solid var(--border-color)",
    borderRadius: "4px",
    padding: "3px 8px",
    fontSize: "10px",
    fontWeight: 600 as const,
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(8, 61, 119, 0.15)",
  },
  btnStopVideo: {
    background: "var(--color-alert)",
    color: "var(--text-light)",
    border: "none",
    borderRadius: "4px",
    padding: "3px 8px",
    fontSize: "10px",
    fontWeight: 600 as const,
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(185, 28, 28, 0.15)",
  },
  redDotRecording: {
    display: "inline-block",
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "var(--color-alert)",
    marginRight: "4px",
    boxShadow: "0 0 4px var(--color-alert)",
  },
  btnStartRecord: {
    background: "var(--bg-primary)",
    color: "var(--color-primary)",
    border: "1px solid var(--color-primary)",
    borderRadius: "4px",
    padding: "3px 8px",
    fontSize: "10px",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(8, 61, 119, 0.1)",
  },
  btnStopRecord: {
    background: "var(--color-primary)",
    color: "var(--text-light)",
    border: "1px solid var(--border-color)",
    borderRadius: "4px",
    padding: "3px 8px",
    fontSize: "10px",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(8, 61, 119, 0.2)",
  },
  pulseRedDot: {
    display: "inline-block",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "var(--color-alert)",
    boxShadow: "0 0 0 0 rgba(185, 28, 28, 0.7)",
  },
  greenDot: {
    display: "inline-block",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "var(--color-success)",
  },
  appContainer: {
    backgroundColor: "var(--bg-primary)",
    color: "var(--text-primary)",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column" as const,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    fontSize: "11px",
  },
  navBar: {
    borderBottom: "1px solid var(--border-color)",
    backgroundColor: "var(--bg-secondary)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 4px",
    height: "26px",
    userSelect: "none" as const,
    minHeight: "26px",
  },
  tabsList: {
    display: "flex",
    listStyle: "none",
    margin: 0,
    padding: 0,
    height: "100%",
    alignItems: "stretch",
  },
  tabItem: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    margin: 0,
    padding: 0,
  },
  link: {
    color: "var(--text-secondary)",
    padding: "0 8px",
    fontSize: "11px",
    fontWeight: "normal",
    height: "100%",
    display: "flex",
    alignItems: "center",
    borderBottom: "2px solid transparent",
    transition: "color 0.2s, border-color 0.2s",
    textDecoration: "none",
  },
  activeLink: {
    color: "var(--color-primary)",
    padding: "0 8px",
    fontSize: "11px",
    fontWeight: "500",
    height: "100%",
    display: "flex",
    alignItems: "center",
    borderBottom: "2px solid transparent",
    textDecoration: "none",
  },
  settingsBtn: {
    padding: "0 6px",
    cursor: "pointer",
    fontSize: "18px",
    color: "var(--color-primary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    transition: "color 0.2s",
    size: "16px",
  },
  themeToggleBtn: {
    padding: "0 6px",
    cursor: "pointer",
    fontSize: "12px",
    color: "var(--color-primary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    transition: "color 0.2s",
  },
  contentBody: {
    padding: "6px",
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflowY: "auto" as const,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center" as const,
    color: "var(--text-secondary)",
    marginTop: "40px",
    padding: "12px",
  },
  emptyTitle: {
    fontSize: "11px",
    fontWeight: "bold",
    color: "var(--color-primary)",
    marginBottom: "2px",
  },
  emptySubtitle: {
    fontSize: "10px",
    maxWidth: "220px",
    lineHeight: "1.3",
  },
  locatorList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
  },
  locatorRow: {
    display: "flex",
    alignItems: "center",
    padding: "3px 4px",
    borderBottom: "1px solid var(--border-color)",
    gap: "4px",
    backgroundColor: "var(--bg-card)",
    borderRadius: "2px",
  },
  labelBox: {
    display: "flex",
    alignItems: "center",
    gap: "3px",
    flexShrink: 1,
    flexGrow: 0,
    width: "84px",
    minWidth: "40px",
    overflow: "hidden",
  },
  priorityBadge: {
    backgroundColor: "var(--bg-primary)",
    color: "var(--color-primary)",
    fontSize: "9px",
    fontWeight: "bold",
    borderRadius: "2px",
    padding: "1px 3px",
    display: "inline-block",
    textAlign: "center" as const,
    minWidth: "12px",
  },
  locatorLabel: {
    fontSize: "10px",
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  codeSnippet: {
    flex: 1,
    minWidth: "20px",
    backgroundColor: "#1e1e1e", // Fixed dark gray editor background
    color: "#d4d4d4", // Fixed default text color
    border: "1px solid #333333", // Fixed dark border
    borderRadius: "2px",
    padding: "2px 4px",
    fontSize: "10px",
    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    cursor: "pointer",
    userSelect: "all" as const,
  },
  actionSelect: {
    appearance: "auto" as any,
    WebkitAppearance: "auto" as any,
    backgroundColor: "var(--bg-secondary)",
    color: "var(--text-primary)",
    border: "1px solid var(--border-color)",
    borderRadius: "2px",
    padding: "1px 2px",
    fontSize: "10px",
    width: "72px",
    minWidth: "72px",
    flexShrink: 0,
    cursor: "pointer",
    outline: "none",
    height: "18px",
  },
  toast: {
    position: "fixed" as const,
    bottom: "12px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 9999,
    padding: "4px 10px",
    borderRadius: "4px",
    boxShadow: "0 2px 8px rgba(8, 61, 119, 0.25)",
    border: "1px solid var(--border-color)",
    background: "var(--color-primary)",
    color: "var(--text-light)",
    fontWeight: "bold",
    fontSize: "10px",
  },
  tableCard: {
    backgroundColor: "var(--bg-card)",
    borderLeft: "3px solid var(--color-primary)",
    padding: "4px 6px",
    marginBottom: "4px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
    borderRadius: "2px",
    borderTop: "1px solid var(--border-color)",
    borderRight: "1px solid var(--border-color)",
    borderBottom: "1px solid var(--border-color)",
  },
  tableHeader: {
    fontSize: "10px",
    fontWeight: "bold",
    color: "var(--color-primary)",
  },
  tableRow: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  tableLabel: {
    fontSize: "9px",
    color: "var(--text-secondary)",
    width: "80px",
    minWidth: "80px",
  },
  tableCode: {
    flex: 1,
    backgroundColor: "#1e1e1e", // Fixed dark gray editor background
    color: "#d4d4d4", // Fixed default text color
    border: "1px solid #333333", // Fixed dark border
    borderRadius: "2px",
    padding: "2px 4px",
    fontSize: "10px",
    fontFamily: "Consolas, Monaco, monospace",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  axesContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    padding: "2px",
  },
  axesResultBox: {
    backgroundColor: "#1e1e1e", // Fixed dark gray editor background
    border: "1px solid #333333", // Fixed dark border
    borderRadius: "2px",
    padding: "4px 6px",
  },
  axesResultCode: {
    color: "var(--color-primary)",
    fontSize: "10px",
    fontFamily: "Consolas, Monaco, monospace",
    fontWeight: "bold",
    cursor: "pointer",
    wordBreak: "break-all" as const,
    background: "none",
    padding: 0,
  },
  axesColumns: {
    display: "flex",
    gap: "4px",
    marginTop: "2px",
  },
  axesColumn: {
    flex: 1,
    border: "1px solid var(--border-color)",
    borderRadius: "2px",
    padding: "4px",
    backgroundColor: "var(--bg-card)",
    maxHeight: "160px",
    overflowY: "auto" as const,
  },
  columnHeader: {
    fontSize: "9px",
    color: "var(--text-secondary)",
    fontWeight: "bold",
    marginBottom: "4px",
    textTransform: "uppercase" as const,
    borderBottom: "1px solid var(--border-color)",
    paddingBottom: "2px",
  },
  radioWrapper: {
    margin: "2px 0",
  },
  radioLabel: {
    color: "var(--text-primary)",
    fontSize: "10px",
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    userSelect: "none" as const,
  },
  toolCard: {
    backgroundColor: "var(--bg-card)",
    border: "1px solid var(--border-color)",
    borderRadius: "2px",
    padding: "6px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
  },
  toolTitle: {
    fontSize: "10px",
    fontWeight: "bold",
    color: "var(--color-primary)",
  },
  toolDesc: {
    fontSize: "9px",
    color: "var(--text-secondary)",
    marginBottom: "2px",
  },
  toolInput: {
    backgroundColor: "var(--bg-secondary)",
    color: "var(--text-primary)",
    border: "1px solid var(--border-color)",
    borderRadius: "2px",
    padding: "2px 4px",
    fontSize: "10px",
    outline: "none",
    flex: 1,
    height: "20px",
  },
  btnFind: {
    border: "none",
    backgroundColor: "var(--color-primary)",
    color: "var(--text-light)",
    padding: "2px 6px",
    fontSize: "10px",
    borderRadius: "2px",
    cursor: "pointer",
    fontWeight: "500",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  btnClear: {
    border: "none",
    backgroundColor: "transparent",
    color: "var(--color-alert)",
    padding: "2px 4px",
    fontSize: "10px",
    cursor: "pointer",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  btnVerifyInline: {
    border: "1px solid var(--color-primary)",
    backgroundColor: "var(--bg-primary)",
    color: "var(--color-primary)",
    padding: "1px 4px",
    fontSize: "9px",
    borderRadius: "2px",
    cursor: "pointer",
    height: "18px",
    width: "32px",
    minWidth: "32px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "4px",
    fontWeight: "500" as any,
  },
  searchSuccess: {
    marginTop: "2px",
    color: "var(--color-success)",
    fontSize: "10px",
  },
  searchFail: {
    marginTop: "2px",
    color: "var(--color-alert)",
    fontSize: "10px",
  },
  convertBox: {
    marginTop: "4px",
    backgroundColor: "var(--bg-secondary)",
    border: "1px solid var(--border-color)",
    padding: "4px",
    borderRadius: "2px",
  },
  convertCode: {
    color: "var(--color-primary)",
    fontSize: "10px",
    fontFamily: "Consolas, Monaco, monospace",
    cursor: "pointer",
    wordBreak: "break-all" as const,
    background: "none",
    padding: 0,
  },
  aboutCard: {
    backgroundColor: "var(--bg-card)",
    border: "1px solid var(--border-color)",
    borderRadius: "2px",
    padding: "8px",
  },
  divider: {
    height: "1px",
    backgroundColor: "var(--border-color)",
    margin: "6px 0",
  },
  linkRow: {
    display: "flex",
    gap: "8px",
  },
  aboutLink: {
    color: "var(--color-primary)",
    fontSize: "10px",
    textDecoration: "none",
  },
};
